
name: Swift

on:
  push:
    branches: [ "ai" ]
  pull_request:
    branches: [ "ma" ]

jobs:
  lint:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: install swiftlint
      run: brew install swiftlint

    - name: run swiftlint
      run: swiftlint

  unit-test:
    needs: lint
    runs-on: macos-latest

    steps:
     - name: checkout the code
       uses: actions/checkout@v4

     - name: Run tests
       run: xcodebuild -scheme MyAppScheme -destination 'platform=macOS' test
  
      
    
