
name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: install swiftlint
      run: brew install swiftlint

    - name: run swiftlint
      run: swiftlint

  unit-test:
    needs: lint
    runs-on: macos-latest

    steps:
     - name: checkout the code
       uses: actions/checkout@v4

     - name: show swift version
       run: swift --version

     - name: run tests
       run: swift test --parallel
  
      
    
